name: "Terraform CI/CD - Medallion Architecture"

on:
  push:
    branches:
      - dev
      - main
  pull_request:
    branches:
      - dev
      - main

jobs:
  validate:
    name: "Terraform Validate"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./IAC

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.9.5"

      - name: Decode GCP Credentials
        run: |
          echo "${{ secrets.KEYGCP }}" | base64 -d > key.json

      - name: Terraform Init & Validate
        run: |
          terraform init -upgrade
          terraform validate
        env:
          GOOGLE_CREDENTIALS: key.json

  plan:
    name: "Terraform Plan"
    needs: validate
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./IAC

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.9.5"

      - name: Decode GCP Credentials
        run: |
          echo "${{ secrets.KEYGCP }}" | base64 -d > key.json

      # run con el archivo env.tfvars.json directo para pruebas:
      # run: |
      #     terraform init
      #     terraform plan -var-file="environment/${{ vars.ENVIRONMENT }}/env.tfvars.json" -out=tfplan

      #run variables de GitHub
      - name: Terraform Init & Plan
        run: |
          terraform init
          terraform plan \
            -var="project=${{ vars.GCP_PROJECT }}" \
            -var="region=${{ vars.GCP_REGION }}" \
            -var="bucket_name=${{ vars.BUCKET_NAME }}" \
            -var="provider=${{ vars.PROVIDER }}" \
            -out=tfplan
        
        env:
          GOOGLE_CREDENTIALS: key.json
        
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: tfplan
          path: IAC/tfplan
          retention-days: 7

  apply:
    name: "Terraform Apply"
    needs: plan
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./IAC

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.9.5"

      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: tfplan
          path: IAC

      - name: Decode GCP Credentials
        run: |
          echo "${{ secrets.KEYGCP }}" | base64 -d > key.json

      - name: Terraform Init & Apply
        run: |
          terraform init
          terraform apply tfplan
        env:
          GOOGLE_CREDENTIALS: key.json